routes/web.php
<?php

use App\Models\Products;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    // 'register'=>false,
    'reset'=>false,
]);

Route::get('/', 'HomeController@index')->name('home');

Route::resource('produk', ProductController::class);
Route::get('/product/data', 'ProductController@fetch_data')->name('product.data');
Route::get('/gallery/{id}/data', 'ProductController@fetch_data_gallery')->name('gallery.data');

Route::resource('produk-galeri', ProductGalleryController::class);
Route::get('/product-galeri/data', 'ProductGalleryController@fetch_data')->name('product-galeri.data');

Route::resource('transaksi', TransactionController::class);
Route::get('/transaction/data', 'TransactionController@fetch_data')->name('transaksi.data');


Route::group(['prefix' => 'dashboard'], function () {
    Route::get('table/{bulan}', 'HomeController@fetch_data');
    Route::get('data', 'HomeController@getDataStatistik');
    Route::get('grafik', 'HomeController@getGrafik');
});

Route::group(['prefix' => 'profil'], function () {
    Route::get('/','ProfileController@index')->name('profil.index');
    Route::post('/','ProfileController@update')->name('profil.update');
});

app/Models/Products.php
<?php

namespace App\Models;

use App\Traits\IdIsUuid;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Products extends Model
{
    //
    use IdIsUuid,SoftDeletes;
    public $incrementing = false;
    protected $fillable =[
        'name','type','description','price','slug','quantity'
    ];
    protected $hidden =[
        'deleted_at','created_at','updated_at'
    ];

    public function galleries()
    {
        return $this->hasMany(ProductGalleries::class,'products_id');
    }

    public function transdetail()
    {
        return $this->hasMany(TransactionDetails::class,'products_id');
    }
}

app/Http/Controllers/API/ProductController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Products;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function all(Request $request)
    {
        $product = Products::with('galleries');

        if($request->id)
            $product->where('id',$request->id);

        if($request->slug)
            $product->where('slug', $request->slug);

        if($request->name)
            $product->where('name','like','%'.$request->nama.'%')->paginate($request->limit?:10)->appends(request()->input());

        if($request->type)
            $product->where('type','like','%'.$request->type.'%')->paginate($request->limit?:10)->appends(request()->input());

        if($request->price_from && $request->price_to)
            $product->whereBetween('price', [$request->price_from, $request->price_to])->orderBy('price',$request->orderby?:'asc')->paginate($request->limit?:10)->appends(request()->input());

        else{
            if($request->price_from)
                $product->where('price', '>=', $request->price_from)->orderBy('price','asc')->paginate($request->limit?:10)->appends(request()->input());

            if($request->price_to)
                $product->where('price','<=',$request->price_to)->orderBy('price','desc');
        }

        if($request->slug || $request->id)
            $data = $product->first();
        else
           $data = $product->paginate($request->limit?:10)->appends(request()->input());

        if($data)
            return ResponseFormater::success($data,'Data produk berhasil ditemukan');
        else
            return ResponseFormater::error(null,'Maaf, Data produk tidak ditemukan',404);

    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\ProductGalleries;
use App\Models\Products;
use App\Models\TransactionDetails;
use App\Models\Transactions;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Products::paginate(10);
        $page=null;
        return view('product.index', compact('data','page'));
    }

    function fetch_data(Request $request)
    {
        if($request->ajax())
        {
           $data = Products::when($request->search, function ($query) use ($request) {
               $query->where('name', 'like', "%{$request->search}%")
                   ->orWhere('type', 'like', "%{$request->search}%")
                   ->orWhere('quantity', 'like', "%{$request->search}%")
                   ->orWhere('price', 'like', "%{$request->search}%");
                })->paginate(10);
            $page=$request->page;
            return view('product.table', compact('data','page'))->render();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ProductRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
            $data = $request->all();
            $data['slug']=Str::slug($request->name);
            Products::create($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\ProductRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
            $data = $request->all();
            $data['slug']=Str::slug($request->name);
            Products::findOrFail($id)->update($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::transaction(function () use($id){
            Products::findOrFail($id)->delete();
            ProductGalleries::where('products_id',$id)->delete();
            $this->destroyTransaction($id);
        });
    }

    protected function destroyTransaction($id)
    {
       $data = TransactionDetails::where('products_id',$id)->get();
       if($data->count() > 0){
           foreach($data as $d){
               Transactions::find($d->transactions_id)->delete();
               TransactionDetails::find($d->id)->delete();
           }
       }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Products::findOrFail($id);
        $data = ProductGalleries::where('products_id',$id)->paginate(10);
        $page=null;
        return view('list-gallery.index', compact('data','page','product'));
    }

    public function fetch_data_gallery(Request $request, $id)
    {
        if($request->ajax())
        {
            $data = ProductGalleries::where('products_id',$id)->paginate(10);
            $page=$request->page;
            return view('list-gallery.table', compact('data','page'))->render();
        }
    }
}

resources/views/product/index.blade.php
@extends('layouts.app')
@section('title')List Product @endsection
@section('header-body')List Product @endsection
@section('breadcrumb')<div class="breadcrumb-item">Produk</div>@endsection


@section('body')
<div class="section-body">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <input type="hidden" id="queryURL">
                    <h4>Daftar Produk</h4>
                    <div class="card-header-action">
                        <button class="btn btn-sm btn-primary" id="tambahBarang"><i class="fas fa-plus-circle"></i> Tambah Produk</button>
                    </div>
                </div>
                <div class="card-body">
                    <input type="hidden" id="formSearch">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search" placeholder="Masukan nama barang untuk mencari Barang dan Tekan Enter untuk memproses">
                    </div>
                    <div id="table_data">
                        @include('product.table')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('end')
<!-- Modal -->
<div class="modal fade" id="modalBarang" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">#</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <form id="myForm" action="#" method="#">
            @csrf<input type="hidden" name="_method" id="method"><input type="hidden" name="id" id="id">
            <div class="modal-body">
                <div class="form-group">
                    <label for="namabarang">Nama Barang</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Masukan Nama Barang">
                    </div>
                </div>
                <div class="form-group">
                    <label for="tipebarang">Tipe Barang</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="type" id="type" placeholder="Masukan Tipe Barang">
                    </div>
                </div>
                <div class="form-group">
                    <label for="deskripsibarang">Deskripsi Barang</label>
                    <div class="input-group">
                        <textarea class="form-control" name="description" id="description" rows="3" placeholder="Masukan Deskripsi Barang"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="hargabarang">Harga Barang</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="price" id="price" placeholder="Masukan Harga Barang">
                    </div>
                </div>
                <div class="form-group">
                    <label for="kuantitasbarang">Kuantitas Barang</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="quantity" id="quantity" placeholder="Masukan Kuantitas Barang">
                    </div>
                </div>
                <br>
                <div class="progress">
                    <div class="bar"></div >
                    <div class="percent">0%</div >
                </div>

                <div id="status"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" id="btnAction" class="btn">Simpan</button>
            </div>
        </form>
        </div>
    </div>
</div>
@endsection

@push('css')
<script src="https://cdn.ckeditor.com/ckeditor5/25.0.0/classic/ckeditor.js"></script>
<style>
    .ck.ck-editor
    {
        width: 100%;
    }
</style>
@endpush

@push('js')
<script src="{{ asset('assets/js/jquery.form.min.js')}}"></script>
@include('product.js')
@endpush

resources/views/product/js.blade.php
<script>
    $(document).on('click', '.pagination a', function(event){
        event.preventDefault();
        var page = $(this).attr('href').split('?')[1];
        $('#queryURL').val(page);
        fetch_data(page);
    });
    function fetch_data(page){
        $.ajax({
            url:"{{route('product.data')}}?"+page,
            success:function(data)
            {
             $('#table_data').html(data);
            }
        });
    }

$("#search").on('keyup', function (e) {
    if (e.key === 'Enter' || e.keyCode === 13) {
        $('#queryURL').val('search='+$(this).val());
    $.ajax({
        url:"{{route('product.data')}}?search="+$(this).val(),
        success:function(data)
        {
         $('#table_data').html(data);
        }
    });
    }
});

$(document).on('click', '.toFoto', function(event){
    var url = $(this).data('url');
    window.location.href = url;
});

$(document).on('click', '.editBarang', function(event){
    $('#name').val($(this).data('name'));
    $('#type').val($(this).data('type'));
    setDataFromTheEditor($(this).data('description'));
    $('#price').val($(this).data('price'));
    $('#quantity').val($(this).data('quantity'));
    $('#modalBarang .modal-title').html('Edit Barang');
    $('#btnAction').html('Edit');
    $('#btnAction').removeClass('btn-primary');
    $("#myForm").attr('action', $(this).data('url'));
    $("#myForm").attr('method', 'PUT');
    $("#method").val('PUT');
    $('#btnAction').addClass('btn-warning');
    $('.progress').hide();
    $('.notifError').remove();
    changeColorValidateCKEditor(false);
    $(':input').removeClass('is-invalid');
    $('#modalBarang').modal('show');
});

$('#tambahBarang').click(function () {
    $('#modalBarang .modal-title').html('Tambah Barang');
    $('#myForm').trigger("reset");
    setDataFromTheEditor('');
    $('#btnAction').html('Simpan');
    $('#btnAction').removeClass('btn-warning');
    $("#myForm").attr('action', '{{route("produk.store")}}');
    $("#myForm").attr('method', 'POST');
    $("#method").val('POST');
    $('.notifError').remove();
    $('#btnAction').addClass('btn-primary');
    $('.progress').hide();
    changeColorValidateCKEditor(false);
    $(':input').removeClass('is-invalid');
    $('#modalBarang').modal('show');
});

$('#btnAction').click(function () {
    $('.notifError').remove();
    changeColorValidateCKEditor(false);
    $(':input').removeClass('is-invalid');
    // $(':textarea').removeClass('is-invalid');
    var bar = $('.bar');
    var percent = $('.percent');
    var urlnya = $('#myForm').attr('action');

    $('#myForm').ajaxForm({
    	url: urlnya,
        beforeSend: function() {
            $('#btnAction').addClass('btn-progress disabled');
            $('#btnAction').attr('disabled','disabled');
            $('.progress').show();
            var percentVal = '0%';
            bar.width(percentVal);
            percent.html(percentVal);
        },
        uploadProgress: function(event, position, total, percentComplete) {
            var percentVal = percentComplete + '%';
            bar.width(percentVal);
            percent.html(percentVal);
        },
    	error: function (response) {
            $('.progress').hide();
            $('#btnAction').removeAttr('disabled');
            $('#btnAction').removeClass('btn-progress disabled');
            $.each(response.responseJSON.errors,function(field_name,error){
                $(document).find('[name='+field_name+']').parent().after('<span class="notifError text-strong text-danger"> <strong>' +error+ '</strong></span>');
                $(document).find('[name='+field_name+']').addClass('is-invalid');
                if(field_name == 'description')changeColorValidateCKEditor(true);
            });
    	},
        success: function(xhr) {
            $('.progress').hide();
            $('#btnAction').removeAttr('disabled');
            $('#btnAction').removeClass('btn-progress disabled');
            $('.notifError').remove();
            changeColorValidateCKEditor(false);
            $(':input').removeClass('is-invalid');
            $('#modalBarang').modal('hide');
            fetch_data($('#queryURL').val());
        }
    });
});

$(document).on('click', '.hapusBarang', function() {
        //// Delete Letter
        var nama = $(this).data('name');
        var urlnya = $(this).data('url');
        swal({
            title: `Hapus Barang?`,
            text: 'Apakah Anda Yakin Menghapus Barang '+nama+'?',
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then( (goPost) =>{
            if(goPost)   {
                $.ajax({
                    url: urlnya,
                    type: "POST",
                    // headers:{
                    //     'Authorization':'Bearer '+ $('#csrf').val(),
                    //     'Accept': 'application/json'
                    // },
                    data: {
                        _token: "{{csrf_token()}}",
                        _method: 'DELETE'
                    },
                    success: function() {
                        swal(" Dihapus!", "Anda berhasil menghapus barang "+nama, "success");
                        fetch_data($('#queryURL').val());
                    },
                    error: function(xhr) {
                        swal("Error "+xhr.status+"!", xhr.responseJSON, "error");
                    }
                });
            }else{
                swal("Batal Dihapus");
            }
        });
    });

let theEditor;
ClassicEditor
    .create( document.querySelector( '#description' ), {
        removePlugins: ['blockQuote', 'italic'],
        toolbar: [ 'Heading','|','bold', 'bulletedList', 'numberedList' , 'Link' ]
    } )
    .then( editor => {
        theEditor = editor; // Save for later use.
    } )
    .catch( error => {
        console.error( error );
    } );

function getDataFromTheEditor() {
    return theEditor.getData();
}
function setDataFromTheEditor(data) {
    return theEditor.setData(data);
}

function changeColorValidateCKEditor(status) {
    if(status){
        $('.ck-editor__editable').css('border-color','#dc3545');
    }else{
        $('.ck-editor__editable').css('border-color','#c4c4c4');
    }
}
</script>

resources/views/product/table.blade.php
<div class="table-responsive">
    <input type="hidden" id="thisPage" value="{{($page)?$page:1}}">
  <table class="table table-striped" width="100%">
    <thead>
      <tr>
          <th width="10%">No.</th>
          <th>Nama Barang</th>
          <th>Tipe Barang</th>
          <th>Harga Barang</th>
          <th width="10%">Ketersediaan</th>
          <th width="15%">Aksi</th>
      </tr>
    </thead>
    <tbody>
        @php
            if($page && $page!= 1){
                $i=($page*10)-10;
            }else{
                $i= 0;
            }
        @endphp
        @forelse ($data as $d)
        <tr>
            <td>{{++$i}}</td>
            <td>{{$d->name}}</td>
            <td>{{$d->type}}</td>
            <td>{{$d->price}}</td>
            <td>{{$d->quantity}}</td>
            <td>
                <button class="btn btn-sm btn-success toFoto" data-url="{{route('produk.show',$d->id)}}"><i class="fas fa-image"></i></button>
                <button class="btn btn-sm btn-warning editBarang"
                   data-name="{{$d->name}}"
                   data-type="{{$d->type}}"
                   data-price="{{$d->price}}"
                   data-quantity="{{$d->quantity}}"
                   data-description="{{$d->description}}"
                   data-url="{{route('produk.update',$d->id)}}"
                >
                    <i class="fas fa-pencil-alt"></i>
                </button>
                <button class="hapusBarang btn btn-sm btn-danger"
                    data-name="{{$d->name}}"
                    data-url="{{route('produk.destroy',$d->id)}}"
                ><i class="fas fa-trash"></i></button>
            </td>
        </tr>
        @empty
        <tr class="text-center text-danger">
            <td colspan="6">Maaf Data Barang tidak ada</td>
        </tr>
        @endforelse
    </tbody>
  </table>
  {!! $data->appends(request()->except('page'))->links() !!}
</div>