routes/web.php
<?php

use App\Models\Products;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    // 'register'=>false,
    'reset'=>false,
]);

Route::get('/', 'HomeController@index')->name('home');

Route::resource('produk', ProductController::class);
Route::get('/product/data', 'ProductController@fetch_data')->name('product.data');
Route::get('/gallery/{id}/data', 'ProductController@fetch_data_gallery')->name('gallery.data');

Route::resource('produk-galeri', ProductGalleryController::class);
Route::get('/product-galeri/data', 'ProductGalleryController@fetch_data')->name('product-galeri.data');

Route::resource('transaksi', TransactionController::class);
Route::get('/transaction/data', 'TransactionController@fetch_data')->name('transaksi.data');


Route::group(['prefix' => 'dashboard'], function () {
    Route::get('table/{bulan}', 'HomeController@fetch_data');
    Route::get('data', 'HomeController@getDataStatistik');
    Route::get('grafik', 'HomeController@getGrafik');
});

Route::group(['prefix' => 'profil'], function () {
    Route::get('/','ProfileController@index')->name('profil.index');
    Route::post('/','ProfileController@update')->name('profil.update');
});

app/Http/Controllers/API/TransactionController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Transactions;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    public function get(Request $request, $id)
    {
        $data = Transactions::with('details.product')->find($id);

        if($data)
            return ResponseFormater::success($data,'data transaksi telah berhasil ditemukan');
        else
            return ResponseFormater::error(null,'data transaksi tidak ditemukan');

    }
}

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TransactionRequest;
use App\Models\TransactionDetails;
use App\Models\Transactions;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TransactionController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Transactions::paginate(10);
        $page=null;
        return view('transaction.index', compact('data','page'));
    }

    public function fetch_data(Request $request)
    {
        if($request->ajax())
        {
           $data = Transactions::when($request->search, function ($query) use ($request) {
               $query->where('kode', 'like', "%{$request->search}%")
                   ->orWhere('name', 'like', "%{$request->search}%")
                   ->orWhere('email', 'like', "%{$request->search}%")
                   ->orWhere('number', 'like', "%{$request->search}%")
                   ->orWhere('transaction_status', 'like', "%{$request->search}%");
                })->paginate(10);
            $page=$request->page;
            return view('transaction.table', compact('data','page'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Transactions::with('details.product')->findOrFail($id);
        return view('transaction.show',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  string  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TransactionRequest $request, $id)
    {
        $data = $request->all();
        Transactions::findOrFail($id)->update($data);
        return response()->json(['status'=>$request->all()]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  string  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::transaction(function () use($id){
            Transactions::findOrFail($id)->delete();
            TransactionDetails::where('transactions_id',$id)->delete();
        });
    }
}

resources/views/transaction/index.blade.php
@extends('layouts.app')
@section('title')List Transaksi @endsection
@section('header-body')List Transaksi @endsection
@section('breadcrumb')<div class="breadcrumb-item">Transaksi</div>@endsection


@section('body')
<div class="section-body">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <input type="hidden" id="queryURL">
                    <h4>Daftar Transaksi</h4>
                    {{-- <div class="card-header-action">
                        <button class="btn btn-sm btn-primary" id="tambahBarang"><i class="fas fa-plus-circle"></i> Tambah Produk</button>
                    </div> --}}
                </div>
                <div class="card-body">
                    <input type="hidden" id="formSearch">
                    <div class="form-group">
                        <input type="text" class="form-control" id="search" placeholder="Masukan kata kunci untuk mencari Transaksi dan Tekan Enter untuk memproses">
                    </div>
                    <div id="table_data">
                        @include('transaction.table')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('end')
<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">sm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                Body
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
            </div>
        </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('assets/js/jquery.form.min.js')}}"></script>
@include('transaction.js')
@endpush

resources/views/transaction/js.blade.php
<script>
$(document).on('click', '.pagination a', function(event){
    event.preventDefault();
    var page = $(this).attr('href').split('?')[1];
    $('#queryURL').val(page);
    fetch_data(page);
});

function fetch_data(page){
    $('#table-body').html('<tr class="text-center"><td colspan="8"><i class="fas fa-spinner fa-pulse"></i> Sedang Memuat Tabel..</td></tr>');
    $.ajax({
        url:"{{route('transaksi.data')}}?"+page,
        success:function(data)
        {
         $('#table_data').html(data);
        }
    });
};

$("#search").on('keyup', function (e) {
    if (e.key === 'Enter' || e.keyCode === 13) {
        $('#queryURL').val('search='+$(this).val());
        $('#table-body').html('<tr class="text-center"><td colspan="8"><i class="fas fa-spinner fa-pulse"></i> Sedang Memuat Tabel..</td></tr>');
    $.ajax({
        url:"{{route('transaksi.data')}}?search="+$(this).val(),
        success:function(data)
        {
         $('#table_data').html(data);
        }
    });
    }
});


$(document).on('click', '.lihatTransaksi', function(){
    var modalID = $('#myModal');
    modalID.find('.modal-title').text('Detail Transaksi '+$(this).data('kode'));
    modalID.find('.modal-body').html('<div class="container text-center"><h4><i class="fas fa-spinner fa-pulse"></i> Sedang Memuat..</h4></div>');
    modalID.modal('show');
    modalID.find('.modal-body').load($(this).data('url'));
});

$(document).on('click', '.hapusTransaksi', function() {
    var nama = $(this).data('name');
    var urlnya = $(this).data('url');
    swal({
        title: `Hapus Transaksi?`,
        text: 'Apakah Anda Yakin Menghapus Transaksi '+nama+'?',
        icon: "warning",
        buttons: true,
        dangerMode: true,
    })
    .then( (goPost) =>{
        if(goPost)   {
            $.ajax({
                url: urlnya,
                type: "POST",
                data: {
                    _token: "{{csrf_token()}}",
                    _method: 'DELETE'
                },
                success: function() {
                    swal(" Dihapus!", "Anda berhasil menghapus Transaksi "+nama, "success");
                    fetch_data($('#queryURL').val());
                },
                error: function(xhr) {
                    swal("Error "+xhr.status+"!", xhr.responseJSON, "error");
                }
            });
        }else{
            swal("Batal Dihapus");
        }
    });
});


$(document).on('click', '.editForm', function(){
    element = $(this).attr('tipenya');
    isi = $(this).attr('isi');
    url = $(this).attr('url');
    place = $(this).attr('title');
    lokasi = $('#'+element);
    jns = (element == 'number')?'number':'text';


    lokasi.html(
        '<form id="'+element+'Form" method="POST"> @method("PUT") @csrf '+
            '<div class="form-group">'+
                '<div class="input-group">'+
                  '<input type="'+jns+'" class="form-control form-control-sm" name="'+element+'" value="'+isi+'" placeholder="'+place.substring(5)+'" required>'+
                  '<div class="input-group-append">'+
                    '<button type="submit" url="'+url+'" isi="'+isi+'" tipenya="'+element+'" title="'+place+'" class="btnSimpan btn btn-sm btn-success" type="button">Simpan</button>'+
                    '<button type="button" url="'+url+'" isi="'+isi+'" tipenya="'+element+'" title="'+place+'" class="btnBatal btn btn-sm btn-secondary" type="button">Batal</button>'+
                  '</div>'+
                '</div>'+
              '</div>'+
        '</form>'
    );
});


$(document).on('click', '.btnBatal', function(){
    element = $(this).attr('tipenya');
    isi = $(this).attr('isi');
    url = $(this).attr('url');
    place = $(this).attr('title');

    lokasi = $('#'+element);
    lokasi.html(
        isi+' <i url="'+url+'" isi="'+isi+'" tipenya="'+element+'" title="'+place+'" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i>'
    );
});

$(document).on('click', '.btnSimpan', function(event){
    event.preventDefault();
    $('.notifError').remove();
    $(':input').removeClass('is-invalid');
    btn=$(this);
    btn.addClass('btn-progress disabled');
    btn.attr('disabled','disabled');
    element = $(this).attr('tipenya');
    urlnya = $(this).attr('url');
    place = $(this).attr('title');
    formName = document.getElementById(element+'Form');
        $.ajax({
          url:urlnya,
          method:"POST",
          contentType: false,
          cache:false,
          processData: false,
          dataType:"json",
          data: new FormData(formName),
          success:function(data)
          {
            isi = $(document).find('[name='+element+']').val();
            lokasi = $('#'+element);
            lokasi.html(
                isi+' <i url="'+url+'" isi="'+isi+'" tipenya="'+element+'" title="'+place+'" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i>'
            );
            console.log(isi);
            fetch_data($('#queryURL').val());
          },
          error: function (response) {
            btn.removeAttr('disabled');
            btn.removeClass('btn-progress disabled');
            $.each(response.responseJSON.errors,function(field_name,error){
                $(document).find('[name='+field_name+']').parent().after('<span class="notifError text-strong text-danger"> <strong>&nbsp;' +error+ '&nbsp;</strong></span>');
                $(document).find('[name='+field_name+']').addClass('is-invalid');
            });
    	}
    });
});

$(document).on('click', '.actionStatus', function() {
    var nama = $(this).data('name');
    var urlnya = $(this).data('url');
    var status = $(this).data('status');
    swal({
        title: `Transaksi `+status+`?`,
        text: 'Apakah Anda Yakin Mengubah status transaksi '+nama+' menjadi '+status+'?',
        icon: "info",
        buttons: true,
        dangerMode: false,
    })
    .then( (goPost) =>{
        if(goPost)   {
            $.ajax({
                url: urlnya,
                type: "POST",
                data: {
                    _token: "{{csrf_token()}}",
                    _method: 'PUT',
                    transaction_status:status
                },
                success: function() {
                    swal("Berhasil!", "Anda berhasil mengubah status Transaksi "+nama, "success");
                    ubahStatus(status);
                    fetch_data($('#queryURL').val());
                },
                error: function(xhr) {
                    swal("Error "+xhr.status+"!", xhr.responseJSON, "error");
                }
            });
        }else{
            swal("Batal Diubah");
        }
    });
});
function ubahStatus(status) {
    if(status == "SUCCESS"){
        $('.statusTran').html('<label class="badge badge-success">'+status+'</label>');
    }else if(status == "PENDING"){
        $('.statusTran').html('<label class="badge badge-info">'+status+'</label>');
    }else if(status == "FAILED"){
        $('.statusTran').html('<label class="badge badge-warning">'+status+'</label>');
    }else{
        $('.statusTran').html('<label>'+status+'</label>');
    }
}
</script>

resources/views/transaction/show.blade.php
<div class="row container mt-2">
    <div class="col-sm-12 col-md-3 col-lg-3">
        <strong>Nama</strong>
    </div>
    <div class="col-sm-12 col-md-9 col-lg-9" id="name">
        {{$data->name}} <i url="{{route('transaksi.update',$data->id)}}" isi="{{$data->name}}" tipenya="name" title="Edit Nama Pemesan" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i>
    </div>
</div>
<div class="row container mt-4">
    <div class="col-sm-12 col-md-3 col-lg-3">
        <strong>Email</strong>
    </div>
    <div class="col-sm-12 col-md-9 col-lg-9" id="email">
        {{$data->email}} <i url="{{route('transaksi.update',$data->id)}}" isi="{{$data->email}}" tipenya="email" title="Edit Email Pemesan" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i>
    </div>
</div>
<div class="row container mt-4">
    <div class="col-sm-12 col-md-3 col-lg-3">
        <strong>Nomer</strong>
    </div>
    <div class="col-sm-12 col-md-9 col-lg-9" id="number">
        {{$data->number}} <i url="{{route('transaksi.update',$data->id)}}" isi="{{$data->number}}" tipenya="number" title="Edit Nomor Pemesan" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i>
    </div>
</div>
<div class="row container mt-4">
    <div class="col-sm-12 col-md-3 col-lg-3">
        <strong>Alamat</strong>
    </div>
    <div class="col-sm-12 col-md-9 col-lg-9" id="address">
        {{$data->address}} <i url="{{route('transaksi.update',$data->id)}}" isi="{{$data->address}}" tipenya="address" title="Edit Alamat Pemesan" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i>
    </div>
</div>
<div class="row container mt-4">
    <div class="col-sm-12 col-md-3 col-lg-3">
        <strong>Total Transaksi</strong>
    </div>
    <div class="col-sm-12 col-md-9 col-lg-9">
        Rp. {{number_format($data->transaction_total, 0, ".", ".")}}
    </div>
</div>
<div class="row container mt-4">
    <div class="col-sm-12 col-md-3 col-lg-3">
        <strong>Status Transaksi</strong>
    </div>
    <div class="col-sm-12 col-md-9 col-lg-9 statusTran">
        @if($data->transaction_status == 'PENDING')
        <label class="badge badge-info">
        @elseif($data->transaction_status == 'SUCCESS')
        <label class="badge badge-success">
        @elseif($data->transaction_status == 'FAILED')
        <label class="badge badge-warning">
        @else
        <label>
        @endif
        {{$data->transaction_status}}
        </label>
    </div>
</div>
<div class="row container mt-4">
    <div class="col-sm-12 col-md-3 col-lg-3">
        <strong>Pembelian</strong>
    </div>
    <div class="col-sm-12 col-md-9 col-lg-9">
        <table class="table table-striped">
            <tr>
                <th>Nama</th>
                <th>Tipe</th>
                <th>Harga</th>
            </tr>
            @foreach ($data->details as $item)
                <tr>
                    <td>{{$item->product->name}}</td>
                    <td>{{$item->product->type}}</td>
                    <td>Rp. {{number_format($item->product->price, 0, ".", ".")}}</td>
                </tr>
            @endforeach
        </table>
    </div>
</div>


{{-- <table class="table table-striped">
    <tr>
        <th>Nama</th>
        <td >{{$data->name}} <i url="{{route('transaksi.update',$data->id)}}" isi="{{$data->name}}" tipenya="name" title="Edit Nama Pemesan" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i></td>
    </tr>
    <tr>
        <th>Email</th>
        <td id="email">{{$data->email}} <i url="{{route('transaksi.update',$data->id)}}" isi="{{$data->email}}" tipenya="email" title="Edit Email Pemesan" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i></td>
    </tr>
    <tr>
        <th>Nomor</th>
        <td id="number">{{$data->number}} <i url="{{route('transaksi.update',$data->id)}}" isi="{{$data->number}}" tipenya="number" title="Edit Nomor Pemesan" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i></td>
    </tr>
    <tr>
        <th>Alamat</th>
        <td id="address">{{$data->address}} <i url="{{route('transaksi.update',$data->id)}}" isi="{{$data->address}}" tipenya="address" title="Edit Alamat Pemesan" class="editForm fas fa-pencil-alt text-warning" style="cursor: pointer"></i></td>
    </tr>
    <tr>
        <th>Total Transaksi</th>
        <td>Rp. {{number_format($data->transaction_total, 0, ".", ".")}}</td>
    </tr>
    <tr>
        <th>Status Transaksi</th>
        <td>
            @if($data->transaction_status == 'PENDING')
            <label class="badge badge-info">
            @elseif($data->transaction_status == 'SUCCESS')
            <label class="badge badge-success">
            @elseif($data->transaction_status == 'FAILED')
            <label class="badge badge-warning">
            @else
            <label>
            @endif
            {{$data->transaction_status}}
            </label>
        </td>
    </tr>
    <tr>
        <th>Pembelian</th>
        <td>
        </td>
    </tr>
</table> --}}
<hr>
<div class="row container text-center">
    <div class="col-4">
        <button class="actionStatus btn btn-sm btn-success"
            data-name="{{$data->kode}}"
            data-status="SUCCESS"
            data-url="{{route('transaksi.update',$data->id)}}">
            <i class="fas fa-check"></i> Set Sukses
        </button>
    </div>
    <div class="col-4">
        <button class="actionStatus btn btn-sm btn-warning"
            data-name="{{$data->kode}}"
            data-status="FAILED"
            data-url="{{route('transaksi.update',$data->id)}}">
            <i class="fas fa-check"></i> Set Gagal
        </button>
    </div>
    <div class="col-4">
        <button class="actionStatus btn btn-sm btn-info"
            data-name="{{$data->kode}}"
            data-status="PENDING"
            data-url="{{route('transaksi.update',$data->id)}}">
            <i class="fas fa-check"></i> Set Pending
        </button>
    </div>
</div>
<hr>

resources/views/transaction/table.blade.php
<div class="table-responsive">
    <input type="hidden" id="thisPage" value="{{($page)?$page:1}}">
  <table class="table table-striped" width="100%">
    <thead>
      <tr>
          <th width="10%" class="text-center">No.</th>
          <th>ID Transaksi</th>
          <th>Nama</th>
          <th>Email</th>
          <th>Nomor</th>
          <th>Total Transaksi</th>
          <th width="10%" class="text-center">Ststus</th>
          <th width="15%" class="text-center">Aksi</th>
      </tr>
    </thead>
    <tbody id="table-body">
        @php
            if($page && $page!= 1){
                $i=($page*10)-10;
            }else{
                $i= 0;
            }
        @endphp
        @forelse ($data as $d)
        <tr>
            <td class="text-center">{{++$i}}</td>
            <td>{{$d->kode}}</td>
            <td>{{$d->name}}</td>
            <td>{{$d->email}}</td>
            <td>{{$d->number}}</td>
            <td>Rp. {{number_format($d->transaction_total, 0, ".", ".")}}</td>
            <td class="text-center">
                @if($d->transaction_status == 'PENDING')
                <button class="btn btn-sm btn-info" style="border-radius: 50px;cursor: default;">
                @elseif($d->transaction_status == 'SUCCESS')
                <button class="btn btn-sm btn-success" style="border-radius: 50px;cursor: default;">
                @elseif($d->transaction_status == 'FAILED')
                <button class="btn btn-sm btn-warning" style="border-radius: 50px;cursor: default;">
                @else
                <button class="btn btn-sm btn-light" style="border-radius: 50px;cursor: default;">
                @endif
                {{$d->transaction_status}}
                </button>
            </td>
            <td class="text-center">
                @if($d->transaction_status == 'PENDING')
                <div class="btn-group">
                    <button class="actionStatus btn btn-sm btn-success"
                        data-name="{{$d->kode}}"
                        data-status="SUCCESS"
                        data-url="{{route('transaksi.update',$d->id)}}">
                        <i class="fas fa-check"></i>
                    </button>
                    <button class="actionStatus btn btn-sm btn-warning"
                        data-name="{{$d->kode}}"
                        data-status="FAILED"
                        data-url="{{route('transaksi.update',$d->id)}}">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
                @endif
                <button class="btn btn-sm btn-light lihatTransaksi"
                    data-kode="{{$d->kode}}"
                    data-url="{{route('transaksi.show',$d->id)}}">
                    <i class="fas fa-eye text-primary"></i></i>
                </button>
                <button class="hapusTransaksi btn btn-sm btn-danger"
                    data-name="{{$d->kode}}"
                    data-url="{{route('transaksi.destroy',$d->id)}}">
                    <i class="fas fa-trash"></i>
                </button>
            </td>
        </tr>
        @empty
        <tr class="text-center text-danger">
            <td colspan="8">Maaf Data Transaksi tidak ada</td>
        </tr>
        @endforelse
    </tbody>
  </table>
  {!! $data->appends(request()->except('page'))->links() !!}
</div>