routes/web.php
<?php

use App\Models\Products;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    // 'register'=>false,
    'reset'=>false,
]);

Route::get('/', 'HomeController@index')->name('home');

Route::resource('produk', ProductController::class);
Route::get('/product/data', 'ProductController@fetch_data')->name('product.data');
Route::get('/gallery/{id}/data', 'ProductController@fetch_data_gallery')->name('gallery.data');

Route::resource('produk-galeri', ProductGalleryController::class);
Route::get('/product-galeri/data', 'ProductGalleryController@fetch_data')->name('product-galeri.data');

Route::resource('transaksi', TransactionController::class);
Route::get('/transaction/data', 'TransactionController@fetch_data')->name('transaksi.data');


Route::group(['prefix' => 'dashboard'], function () {
    Route::get('table/{bulan}', 'HomeController@fetch_data');
    Route::get('data', 'HomeController@getDataStatistik');
    Route::get('grafik', 'HomeController@getGrafik');
});

Route::group(['prefix' => 'profil'], function () {
    Route::get('/','ProfileController@index')->name('profil.index');
    Route::post('/','ProfileController@update')->name('profil.update');
});

app/Http/Controllers/ProductGalleryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductGalleryRequest;
use App\Models\ProductGalleries;
use App\Models\Products;
use Illuminate\Http\Request;

class ProductGalleryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = ProductGalleries::with('product')->paginate(10);
        $page=null;
        $barang = Products::all();
        return view('product-gallery.index', compact('data','page','barang'));
    }

    public function fetch_data(Request $request)
    {
        if($request->ajax())
        {
            $data = ProductGalleries::paginate(10);
            $page=$request->page;
            return view('product-gallery.table', compact('data','page'))->render();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ProductGalleryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductGalleryRequest $request)
    {
            $data = $request->all();
            $data['photo']=$request->file('photo')->store(
                'assets/product','public'
            );
            ProductGalleries::create($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        ProductGalleries::findOrFail($id)->delete();
    }
}

resources/views/product-gallery/index.blade.php
@extends('layouts.app')
@section('title')List Product Gallery @endsection
@section('header-body')List Product Gallery @endsection
@section('breadcrumb')<div class="breadcrumb-item">Produk Gallery</div>@endsection


@section('body')
<div class="section-body">
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
            <h4>Daftar Produk Galeri</h4>
            <div class="card-header-action">
                <button class="btn btn-sm btn-primary" id="tambahBarang"><i class="fas fa-plus-circle"></i> Tambah Foto </button>
            </div>
        </div>
        <div class="card-body">
            <div id="table_data">
                @include('product-gallery.table')
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

@section('end')
<!-- Modal -->
<div class="modal fade" id="modalBarang" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">#</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <form id="myForm" action="#" method="#" enctype="multipart/form-data">
            @csrf<input type="hidden" name="_method" id="method">
            <div class="modal-body">
                <div class="form-group">
                  <label for="products_id">Nama Barang</label>
                  <select class="form-control" name="products_id" id="products_id">
                      <option value="">-- Pilih Nama Barang --</option>
                    @foreach ($barang as $i)
                        <option value="{{$i->id}}">{{$i->name}}</option>
                    @endforeach
                  </select>
                </div>
                <div class="form-group">
                  <label for="phot">Foto Product</label>
                  <input type="file" class="form-control" name="photo" id="photo" placeholder="foto produk" aria-describedby="fileHelpId">
                </div>
                <div class="form-group">
                    <label for="">Jadikan Default ?</label><br>
                    <div class="form-check form-check-inline">
                        <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="is_default" value="1" checked>
                        Yes
                      </label>
                    </div>
                    <div class="form-check form-check-inline">
                        <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="is_default" value="0">
                        No
                      </label>
                    </div>
                </div>
                <div id="lihatGambar"></div>
                <br>
                <div class="progress">
                    <div class="bar"></div >
                    <div class="percent">0%</div >
                </div>
                <div id="status"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" id="btnAction" class="btn">Simpan</button>
            </div>
        </form>
        </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('assets/js/jquery.form.min.js')}}"></script>
@include('product-gallery.js')
@endpush

resources/views/product-gallery/js.blade.php
<script>
    $(document).on('click', '.pagination a', function(event){
        event.preventDefault();
        var page = $(this).attr('href').split('page=')[1];
        fetch_data(page);
    });
    function fetch_data(page){
        $.ajax({
            url:"{{route('product-galeri.data')}}?page="+page,
            success:function(data)
            {
             $('#table_data').html(data);
            }
        });
    }

$('#tambahBarang').click(function () {
    $('#modalBarang .modal-title').html('Tambah Foto Barang');
    $('#myForm').trigger("reset");
    $('#btnAction').html('Simpan');
    $('#btnAction').removeClass('btn-warning');
    $("#myForm").attr('action', '{{route("produk-galeri.store")}}');
    $("#myForm").attr('method', 'POST');
    $("#method").val('POST');
    $('#btnAction').addClass('btn-primary');
    $('.progress').hide();
    $('.notifError').remove();
    $(':input').removeClass('is-invalid');
    $('#modalBarang').modal('show');
});

$('#btnAction').click(function () {
    $('.notifError').remove();
    $(':input').removeClass('is-invalid');
    var bar = $('.bar');
    var percent = $('.percent');
    var urlnya = $('#myForm').attr('action');

    $('#myForm').ajaxForm({
    	url: urlnya,
        beforeSend: function() {
    $('#btnAction').addClass('btn-progress disabled');
    $('#btnAction').attr('disabled','disabled');
            $('.progress').show();
            var percentVal = '0%';
            bar.width(percentVal);
            percent.html(percentVal);
        },
        uploadProgress: function(event, position, total, percentComplete) {
            var percentVal = percentComplete + '%';
            bar.width(percentVal);
            percent.html(percentVal);
        },
    	error: function (response) {
            $('.progress').hide();
            $('#btnAction').removeAttr('disabled');
            $('#btnAction').removeClass('btn-progress disabled');
            $.each(response.responseJSON.errors,function(field_name,error){
                $(document).find('[name='+field_name+']').after('<span class="notifError text-strong text-danger"> <strong>' +error+ '</strong></span>');
                $(document).find('[name='+field_name+']').addClass('is-invalid');
            });
    	},
        success: function(xhr) {
            $('.progress').hide();
            $('#btnAction').removeAttr('disabled');
            $('#btnAction').removeClass('btn-progress disabled');
            $('.notifError').remove();
            $(':input').removeClass('is-invalid');
            $('#modalBarang').modal('hide');
            fetch_data($('#thisPage').val());
        }
    });
});

$(document).on('click', '.hapusBarang', function() {
        //// Delete Letter
        var nama = $(this).data('name');
        var urlnya = $(this).data('url');
        swal({
            title: `Hapus Barang?`,
            text: 'Apakah Anda Yakin Menghapus Foto Barang '+nama+'?',
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
        .then( (goPost) =>{
            if(goPost)   {
                $.ajax({
                    url: urlnya,
                    type: "POST",
                    // headers:{
                    //     'Authorization':'Bearer '+ $('#csrf').val(),
                    //     'Accept': 'application/json'
                    // },
                    data: {
                        _token: "{{csrf_token()}}",
                        _method: 'DELETE'
                    },
                    success: function() {
                        swal(" Dihapus!", "Anda berhasil menghapus Foto barang "+nama, "success");
                        fetch_data($('#thisPage').val());
                    },
                    error: function(xhr) {
                        swal("Error "+xhr.status+"!", xhr.responseJSON, "error");
                    }
                });
            }else{
                swal("Batal Dihapus");
            }
        });
    });
</script>

resources/views/product-gallery/table.blade.php
<div class="table-responsive">
    <input type="hidden" id="thisPage" value="{{($page)?$page:1}}">
  <table class="table table-striped" width="100%">
    <thead>
      <tr>
          <th width="10%">No.</th>
          <th>Nama Barang</th>
          <th>Foto</th>
          <th width="5%">Default</th>
          <th width="15%">Aksi</th>
      </tr>
    </thead>
    <tbody>
        @php
            if($page && $page!= 1){
                $i=($page*10)-10;
            }else{
                $i= 0;
            }
        @endphp
        @forelse ($data as $d)
        <tr>
            <td>{{++$i}}</td>
            <td>{{$d->product->name}}</td>
            <td>
                <img src="{{url($d->photo)}}" width="50px" style="cursor: pointer" alt="photo {{$d->product->name}}">
            </td>
            <td>{!! $d->is_default?'<label class="badge badge-success">Yes</label>':'<label class="badge badge-danger">Tidak</label>' !!}</td>
            <td>
                <button class="hapusBarang btn btn-sm btn-danger"
                    data-name="{{$d->product->name}}"
                    data-url="{{route('produk-galeri.destroy',$d->id)}}"
                ><i class="fas fa-trash"></i></button>
            </td>
        </tr>
        @empty
        <tr class="text-center text-danger">
            <td colspan="5">Maaf, Data Foto Barang tidak ada</td>
        </tr>
        @endforelse
    </tbody>
  </table>
  {!! $data->links() !!}
</div>